import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const manifest = read('manifest.yml');
const backend = read('src/index.js');
const app = read('static/hello-world/src/App.js');
const css = read('static/hello-world/src/App.css');
const assistantNormalize = read('static/hello-world/src/assistant/normalize.mjs');
const assistantSmallTalk = read('static/hello-world/src/assistant/smallTalk.mjs');
const assistantContext = read('static/hello-world/src/assistant/contextResolver.mjs');
const assistantEntity = read('static/hello-world/src/assistant/entityResolver.mjs');
const assistantIntent = read('static/hello-world/src/assistant/intentResolver.mjs');
const assistantResponse = read('static/hello-world/src/assistant/responseBuilder.mjs');
const assistantActions = read('static/hello-world/src/assistant/actions.mjs');
const assistantAgileKnowledge = read('static/hello-world/src/assistant/agileKnowledge.mjs');
const permissionsDoc = read('docs/PERMISSIONS.md');
const limitationsDoc = read('docs/KNOWN_LIMITATIONS.md');
const deploymentDoc = read('docs/DEPLOYMENT.md');
const securityDoc = read('docs/SECURITY.md');
const retentionDoc = read('docs/DATA_RETENTION.md');
const privacyFlowDoc = read('docs/PRIVACY_AND_DATA_FLOW.md');

const scheduleTimeRegex = /^([01]\d|2[0-3]):[0-5]\d$/;
const assistantProjectPhraseRegex = /(?:in|for|of|about|from)\s+["']?(.+?)["']?\s+project\b/i;
const assistantScopeFirstRegex = /(?:summary|status|details?|overview|report)\s+(?:of|for|on|about)\s+["']?([^,?.:;!]+?)["']?(?=\s+(?:sprint|board)\b|[,.?]|$)/i;
const confluencePageIdRegex = /[?&](?:pageId|homepageId)=(\d+)/i;

const checks = [
  ['Acceptance Criteria source fields hydrate from Jira Platform search when Sprint API returns zero/missing AC', backend.includes('hydrateAcceptanceCriteriaIssueFields') && backend.includes('acceptance_criteria_fields_hydrated') && backend.includes('Hydrating Acceptance Criteria source fields')],
  ['Acceptance Criteria hydration is bounded to Story keys rather than per-issue REST calls', backend.includes('key in (${chunk.join(',')})') && backend.includes('offset += 100')],
  ['Sprint report cache bumped after Acceptance Criteria hydration fix', backend.includes('report-cache-v6:')],
  ['Production package excludes backup directory', !fs.existsSync(path.join(root, 'backup'))],
  ['Production package excludes root node_modules', !fs.existsSync(path.join(root, 'node_modules'))],
  ['Production package excludes frontend node_modules', !fs.existsSync(path.join(root, 'static/hello-world/node_modules'))],
  ['Generated frontend build is not committed', !fs.existsSync(path.join(root, 'static/hello-world/build'))],
  ['Dedicated Assistant scenario suite included', fs.existsSync(path.join(root, 'scripts/assistant-scenarios.mjs'))],
  ['global page preserved', manifest.includes('jira:globalPage')],
  ['project page preserved', manifest.includes('jira:projectPage')],
  ['board action preserved', manifest.includes('jira:boardAction')],
  ['backlog action preserved', manifest.includes('jira:backlogAction')],
  ['dashboard gadget preserved', manifest.includes('jira:dashboardGadget')],
  ['licensing preserved', manifest.includes('licensing:') && manifest.includes('enabled: true')],
  ['storage scope preserved', manifest.includes('storage:app')],
  ['Sprint report resolver preserved', backend.includes("'getSprintReport'")],
  ['Velocity resolver preserved', backend.includes("'getVelocityReport'")],
  ['Usage resolver preserved', backend.includes("'getUsageStatus'")],
  ['License resolver preserved', backend.includes("'getLicenseStatus'")],
  ['Board config resolver preserved', backend.includes("'getBoardReportingConfiguration'")],
  ['Reporting settings resolver preserved', backend.includes("'saveReportingSettings'")],
  ['Commentary resolver preserved', backend.includes("'saveCommentaryOverlay'")],
  ['Scheduler settings resolver preserved', backend.includes("'saveReportSchedule'")],
  ['No HDP hardcode', !app.includes("project.key === 'HDP'")],
  ['PowerPoint export preserved', app.includes('createPowerPoint') && app.includes('handlePowerPointExport')],
  ['PDF export preserved', app.includes('createPdfReport') && app.includes('handlePdfExport')],
  ['Full export still includes Burndown', app.includes('burndown: true') && app.includes('FULL_EXPORT_SECTIONS')],
  ['Project/program report preserved', app.includes('Project / Program Report')],
  ['Estimation detection UI preserved', app.includes('Estimation Source Detected From Jira Board')],
  ['Draft/publish commentary preserved', (app.includes("saveCommentary('draft'") || app.includes("onSaveCommentary('draft'")) && (app.includes("saveCommentary('published'") || app.includes("onSaveCommentary('published'"))],
  ['Return to Green preserved', app.includes('Return to Green') && app.includes('buildReturnToGreen')],
  ['Local assistant preserved', app.includes('StatusDeck Assistant') && app.includes('assistant-panel-chat')],
  ['Legacy Confluence/SharePoint copy action removed', !app.includes('Copy for Confluence / SharePoint') && !app.includes('copyReportForCollaboration')],

  ['Native top-level section dragging retired', !app.includes('setDraggedReportSection') && app.includes("draggable: false")],
  ['Section dots open deterministic move menu', app.includes('sectionMoveMenu') && app.includes('MoveMenu') && app.includes('moveReportSectionByDirection')],
  ['Section menu exposes four directions', app.includes("['up', '↑', 'Move Up']") && app.includes("['down', '↓', 'Move Down']") && app.includes("['left', '←', 'Move Left']") && app.includes("['right', '→', 'Move Right']")],
  ['Top-level section Up/Down changes saved order', app.includes("direction !== 'up' && direction !== 'down'") && app.includes('[next[from], next[to]] = [next[to], next[from]]')],
  ['Fresh top-level section preference resets flaky drag order', app.includes('statusdeck-section-order-v3') && !app.includes("getItem('statusdeck-section-order-v2')")],

  ['Overview uses React-state command movement instead of drag hit-testing', app.includes('Executive Overview movement is React-state-driven') && app.includes('overviewOrder') && app.includes('overviewMoveMenu')],
  ['Overview movement does not inject React-owned DOM children', !app.includes('card.insertBefore(') && !app.includes("document.createElement('button')") && !app.includes("document.createElement('div')")],
  ['Only overview logical blocks get React move controls', app.includes("overviewHandleProps('management-commentary'") && app.includes("overviewHandleProps('return-to-green'") && !app.includes('const groupSelectors = [')],
  ['Overview move menu reuses React portal menu with four directions', app.includes('availability={overviewMovementState(overviewMoveMenu.cardId)}') && app.includes('onMove={(direction) => moveOverviewCardByDirection(overviewMoveMenu.cardId, direction)}')],
  ['Overview Left/Right swaps same-row peers', app.includes("direction === 'left' && availability.left") && app.includes("direction === 'right' && availability.right")],
  ['Overview Up/Down swaps deterministic row/column positions', app.includes('targetRowIndex') && app.includes('targetColumn') && app.includes('const nextVisible = rows.flat()')],
  ['Fresh overview order preference resets broken experimental layout', app.includes('statusdeck-overview-layout-order-v1') && !app.includes('statusdeck-card-order-v3:')],
  ['Management Commentary defaults first', app.indexOf('data-card-id="management-commentary"') >= 0 && app.indexOf('data-card-id="management-commentary"') < app.indexOf('data-card-id="sprint-health-core"')],
  ['Management Commentary remains full width', app.includes('overview-span-12 statusdeck-movable-card" data-card-id="management-commentary"') && css.includes('.overview-span-12 {')],
  ['Sprint Health remains full width and owns core KPIs', app.includes('overview-span-12 statusdeck-movable-card" data-card-id="sprint-health-core"') && app.includes('sprint-health-kpi-grid') && app.includes('Delivery Progress & Core KPIs')],
  ['Core KPI labels remain grouped', app.includes('label="Completed"') && app.includes('label="Remaining"') && app.includes("'Delivery Risk'")],
  ['Risk and Scope Health remain half-width peers', app.includes('overview-span-6 statusdeck-movable-card" data-card-id="risk-profile"') && app.includes('overview-span-6 statusdeck-movable-card" data-card-id="scope-health"')],
  ['Work Distribution and Capacity remain half-width peers', app.includes('overview-span-6 statusdeck-movable-card" data-card-id="work-distribution"') && app.includes('overview-span-6 statusdeck-movable-card" data-card-id="capacity-view"')],
  ['Velocity and Return to Green remain overview blocks', app.includes('overview-span-6 statusdeck-movable-card" data-card-id="velocity-summary"') && app.includes('overview-span-6 statusdeck-movable-card" data-card-id="return-to-green"')],
  ['Overview grid respects logical order rather than dense backfill', css.includes('grid-auto-flow: row;') && !css.includes('grid-auto-flow: row dense;')],

  ['Compact live Burndown remains inside Sprint Health', app.includes('sprint-health-burndown') && app.includes('Live / Intraday Jira-Event Trajectory') && app.includes('compactLiveBurndownPoints')],
  ['Compact Burndown uses event-level live data', app.includes('history?.burndownLive') && app.includes('view="live"') && app.includes('Live Events')],
  ['Detailed web Burndown restored as a separate section', app.includes("id: 'burndown'") && app.includes("label: 'Detailed Burndown'") && app.includes('<h3>Detailed Sprint Burndown</h3>')],
  ['Detailed Burndown supports Daily and Live event modes', app.includes("setBurndownView(\n                          'daily'") && app.includes("setBurndownView(\n                          'live'")],
  ['Detailed Burndown supports Story Points and Remaining Effort', app.includes("setBurndownBasis(\n                          'points'") && app.includes("setBurndownBasis(\n                          'effort'")],
  ['Detailed Burndown is no longer disabled behind false guard', !app.includes('{false && history?.available ? (')],
  ['Burndown export path preserved', app.includes("if (selectedSections.burndown && report.history?.available)")],
  ['Compact live Burndown height constrained', css.includes('height: clamp(220px, 22vw, 260px);') && css.includes('max-height: 260px;')],
  ['Detailed Burndown web height remains capped', css.includes('height: clamp(280px, 29vw, 340px);') && css.includes('max-height: 340px;')],
  ['Detailed Burndown export/chart sizing code preserved', app.includes('const height = 320;') && app.includes('preserveAspectRatio="xMidYMid meet"')],

  ['Publish success feedback shown beside commentary actions', app.includes('Published successfully.') && app.includes('commentary-save-feedback') && app.includes('role="status"')],
  ['Publish failure feedback shown beside commentary actions', app.includes('Publish failed:') && css.includes('.commentary-save-feedback-error')],
  ['Executive commentary is scannable at a glance', app.includes('function ExecutiveCommentaryPreview') && app.includes('executive-status-badge') && app.includes('KEY RISKS') && app.includes('RECOMMENDED ACTIONS') && css.includes('.executive-commentary-callouts')],
  ['Executive commentary editor is opt-in instead of the default view', app.includes("showCommentaryEditor") && app.includes("'Edit commentary'") && app.includes('executive-commentary-edit-panel')],
  ['Executive commentary exports use status and metric callouts', app.includes('getExecutiveCommentarySnapshot') && app.includes('At-a-glance sprint status, risks, actions and next-sprint outlook') && app.includes('NEXT SPRINT OUTLOOK')],
  ['Commentary export blocks stale saved commentary and uses current snapshot', app.includes('const commentaryForExport = commentaryStale') && app.match(/managementCommentaryText: commentaryForExport/g)?.length >= 4 && app.includes('reportFingerprint: currentReportFingerprint')],
  ['PowerPoint export parses full commentary text', app.includes('parseManagementCommentaryForExport') && app.includes('commentaryContinuationLines') && app.includes('Executive Commentary · Continued')],
  ['PDF export preserves commentary continuation', app.includes("'Executive Commentary · Continued'") && app.includes('continuationLines = doc.splitTextToSize')],
  ['Planning checks are preserved in exported commentary', app.includes("['planning checks', 'planning']") && app.includes('commentarySections.planning') && app.includes('PLANNING CHECKS · CONTINUED')],

  ['Calculation help component preserved', app.includes('function CalculationButton') && app.includes('getCalculationHelp')],
  ['Calculation tooltip uses body portal', app.includes("import { createPortal } from 'react-dom';") && app.includes('calculation-popover-portal') && app.includes('document.body')],
  ['Calculation tooltip opens on hover and keyboard focus', app.includes('onMouseEnter={showTooltip}') && app.includes('onFocus={showTooltip}') && app.includes('onBlur={hideTooltip}')],
  ['Calculation tooltip also opens on pointer hover', app.includes('onPointerEnter={showTooltip}') && app.includes('onPointerLeave={hideTooltip}')],
  ['Calculation help has native browser hover fallback', app.includes('title={nativeTooltip}') && app.includes('const nativeTooltip =')],
  ['Calculation help has click fallback', app.includes('onClick={toggleTooltip}') && app.includes('function toggleTooltip(event)')],
  ['Metric decoration cannot intercept calculation hover', css.includes('.metric-card::after {\n  pointer-events: none;')],
  ['Calculation trigger is explicitly pointer interactive', css.includes('.calculation-help-button {\n  position: relative;') && css.includes('pointer-events: auto;') && css.includes('touch-action: manipulation;')],
  ['Calculation tooltip is viewport-positioned', app.includes('getBoundingClientRect()') && css.includes('.calculation-popover.calculation-popover-portal') && css.includes('position: fixed;')],
  ['Delivery completion calculation help present', app.includes('calculationKey="completion"') || app.includes("calculationKey={report.sprint.state === 'future' ? 'planningReadiness' : 'completion'}")],
  ['Delivery health calculation help present', app.includes('calculationKey="health"')],
  ['Scope calculation help present', app.includes('calculationKey="scopeCurrent"') && app.includes('calculationKey="scopeEstimateChange"')],
  ['Effort calculation help present', app.includes('calculationKey="remaining"') && app.includes('calculationKey="forecast"') && app.includes('calculationKey="variance"')],
  ['Coverage calculation help present', app.includes('calculationKey="originalCoverage"') && app.includes('calculationKey="remainingCoverage"') && app.includes('calculationKey="spentCoverage"')],
  ['Velocity calculation help present', app.includes('calculationKey="velocity"')],

  ['Move menu CSS present', css.includes('.statusdeck-move-menu {') && css.includes('.statusdeck-move-menu-item')],
  ['Move handles use click cursor', css.includes('.report-section-drag-handle,') && css.includes('cursor: pointer;')],
  ['Legacy pointer-drag listener removed', !app.includes("window.addEventListener('pointermove', onPointerMove, true)")],
  ['Top-level report remains normal single-column flow', css.includes('.report-layout-grid .report-main') && css.includes('grid-template-columns: minmax(0, 1fr);')],
  ['Legacy masonry span calculation remains removed', !app.includes('statusdeckGridSpan = String(span)') && !app.includes('gridRowEnd = `span ${span}`')],
  ['Configuration edits are isolated inside modal component', app.includes('function ReportingSettingsModal') && app.includes('const [draft, setDraft] = useState') && !app.includes('reportingSettingsDraft')],
  ['Estimation selection changes modal-local draft only', app.includes("value={draft.estimationOverride || ''}") && app.includes('const value = event.currentTarget.value; setDraft((current) => ({ ...current, estimationOverride: value }))')],
  ['React 16 configuration handlers capture values before functional state updates', !/setDraft\(\([^)]*\) =>[^\n]*(?:event|e)\.target\.(?:value|checked)/.test(app) && app.includes('greenCompletion: Number(value)') && app.includes('maximumVelocityLoad: Number(value)')],
  ['React 16 schedule handlers capture values before functional state updates', !/setReportSchedule\(\([^)]*\) =>[^\n]*(?:event|e)\.target\.(?:value|checked)/.test(app) && app.includes('enabled: checked') && app.includes('cadence: value')],
  ['Configuration event handlers use currentTarget capture', (app.match(/const value = event\.currentTarget\.value/g) || []).length >= 9],
  ['Configuration relationships validated client-side', app.includes('Amber completion must be less than or equal to Green completion.') && app.includes('Amber unresolved defects must be less than or equal to Red unresolved defects.') && app.includes('Amber overdue items must be less than or equal to Red overdue items.')],
  ['Configuration relationships validated server-side', backend.includes('function validateReportingSettings(settings)') && backend.includes('const settings = validateReportingSettings(payload?.settings);')],
  ['Configuration validation errors stay visible in isolated modal', app.includes('settings-validation-message') && app.includes('notice.message') && app.includes('role="alert"')],
  ['Estimation override is sent to sprint report resolver', app.includes("invoke('getSprintReport'") && app.includes("estimationOverride: effectiveSettings.estimationOverride || ''")],
  ['Estimation override is sent to velocity resolver', app.includes("invoke('getVelocityReport'") && app.includes("estimationOverride: effectiveSettings.estimationOverride || ''")],
  ['Estimation override is sent to next-sprint outlook resolver', app.includes("invoke('getNextSprintOutlook'") && app.includes("currentSprintId: Number(sprintId)")],
  ['Project report also applies estimation override', app.includes('boardId: Number(board.id)') && app.includes('estimationOverride: effectiveSettings.estimationOverride')],
  ['Backend supports issue-count estimation override', backend.includes('ISSUE_COUNT_ESTIMATION_FIELD_ID') && backend.includes("type: 'issueCount'")],
  ['Backend supports Original Estimate override in hours', backend.includes('ORIGINAL_ESTIMATE_FIELD_ID') && backend.includes("type: 'originalEstimate'") && backend.includes("unit: 'hours'")],
  ['Backend validates selected custom estimation field', backend.includes('selected estimation override is no longer available as a numeric Jira field') && backend.includes("['number', 'integer'].includes(schemaType)")],
  ['Use Jira board setting resolves board estimation source', backend.includes('Loading board estimation configuration') && backend.includes("source: 'jira-board'")],
  ['Report cache is partitioned by estimation source', backend.includes("safeIdentifier(estimationOverride || 'board-default')") && backend.includes("boardId = 'none'")],
  ['Special synthetic estimation ids are never requested from Jira', backend.includes('requestableEstimationFieldId') && backend.includes("value.startsWith('__statusdeck_')")],
  ['History uses selected estimation field values', backend.includes('estimationValueFromHistoryItem') && backend.includes('estimationPreviousValueFromHistoryItem')],
  ['Report exposes effective estimation source', backend.includes('estimationSource,') && backend.includes('unit: estimationSource.unit')],
  ['Failed reload preserves the existing visible report', !app.substring(app.indexOf('async function loadReport'), app.indexOf('const selectedProject', app.indexOf('async function loadReport'))).includes('setReport(null)')],
  ['Completion thresholds drive visible progress tone', app.includes('const completionTone = useMemo') && app.includes('completion >= green') && app.includes('completion >= amber') && app.includes('sprint-progress-fill-${completionTone')],
  ['Sprint Health delivery progress uses configured completion tone', app.includes("tone={report.sprint.state === 'future' ? planningAssessment.tone : completionTone}")],
  ['Progress ring reflects configured completion tone', css.includes('.progress-ring-warning .progress-ring-circle') && css.includes('.progress-ring-negative .progress-ring-circle')],
  ['Unresolved defect and overdue thresholds drive Delivery Risk tone', app.includes('const deliveryRiskTone = useMemo') && app.includes('rag.redOpenDefects') && app.includes('rag.amberOverdue')],
  ['Delivery Risk drills into unresolved defects only', app.includes('openDefects: displayedIssues') && app.includes('issueGroups.openDefects')],
  ['Minimum Remaining Estimate coverage remains live-configured', app.includes('reportingSettings.rag?.minimumRemainingEstimateCoverage ?? 80') && app.includes('forecastProvisional: coverage < minimumCoverage')],
  ['Maximum next-sprint velocity load now uses configuration', app.includes('reportingSettings.readiness?.maximumVelocityLoad ?? 115') && app.includes('velocityLoadPercentage > maximumVelocityLoad')],
  ['Estimation source changes refresh report transactionally after save', app.includes('const estimationChanged =') && app.includes('await loadReport(mergedSaved, { throwOnError: true })')],
  ['KPI-only changes avoid unnecessary native Jira report reload', app.includes('else if (customKpiChanged && (report || projectReport))') && app.includes('await refreshCustomInsightsOnly(mergedSaved);') && !app.includes('if ((estimationChanged || kpiProfileChanged) && (report || projectReport))')],
  ['Estimation labels adapt for items, hours and points', app.includes('function getEstimationDisplay(report)') && app.includes("noun: 'estimate hours'") && app.includes("noun: 'story points'")],
  ['V1 UI baseline remains command-move based', app.includes('Move Up') && app.includes('Move Down') && app.includes('Management Commentary')],
  ['Configuration edits do not rerender report-owned draft state', app.includes('function ReportingSettingsModal') && !app.includes('setReportingSettingsDraft') && !app.includes('card.insertBefore(')],
  ['Overview order is applied with React style props', app.includes("style={overviewCardStyle('management-commentary')}") && app.includes("style={overviewCardStyle('return-to-green')}" )],
  ['Overview move controls are React-managed buttons', app.match(/className="statusdeck-card-drag-handle no-export"/g)?.length >= 7],

  ['Configuration modal owns its own saving and notice state', app.includes('const [saving, setSaving] = useState(false);') && app.includes('const [notice, setNotice] = useState(null);')],
  ['Configuration modal saves through parent callback only', app.includes('const outcome = await onSave(candidate);') && app.includes('onSave={saveReportingSettings}')],
  ['Estimation save is transactional before live settings commit', app.indexOf('await loadReport(mergedSaved, { throwOnError: true })') >= 0 && app.indexOf('await loadReport(mergedSaved, { throwOnError: true })') < app.indexOf('setReportingSettings(mergedSaved)')],
  ['Failed estimation refresh rolls persisted settings back', app.includes("console.warn('Unable to roll back StatusDeck reporting settings'") && app.includes('settings: previousSettings')],
  ['Report loader can rethrow transactional configuration failures', app.includes('async function loadReport(settingsOverride = null, options = {})') && app.includes('if (options?.throwOnError)')],
  ['Project report loader is also transactional for configuration changes', app.includes('async function loadProjectLevelReport(settingsOverride = null, options = {})') && app.includes('return loadProjectLevelReport(effectiveSettings, options);')],
  ['React error boundary prevents a white-screen-only failure', app.includes('class StatusDeckErrorBoundary extends React.Component') && app.includes('StatusDeck Could Not Render This View') && app.includes('Reload StatusDeck')],
  ['Global and gadget views are wrapped by error boundary', app.match(/<StatusDeckErrorBoundary>/g)?.length >= 2],
  ['Fatal recovery CSS present', css.includes('.statusdeck-fatal-error-card') && css.includes('.statusdeck-fatal-error-message')],
  ['Overall RAG is visible in Executive Pulse', app.includes('Overall RAG') && app.includes('overallRag={overallRag}') && css.includes('.overall-rag-pill')],
  ['Overall RAG uses configured thresholds', app.includes('function getOverallRag') && app.includes('rag.redOverdue') && app.includes('rag.redOpenDefects') && app.includes('rag.greenCompletion')],
  ['Scheduler exact-minute validation accepts HH:mm', backend.includes("/^([01]\\d|2[0-3]):[0-5]\\d$/") && !backend.includes("/^([01]\\\\d|2[0-3]):[0-5]\\\\d$/")],
  ['Scheduler exact-minute validator behaves correctly', scheduleTimeRegex instanceof RegExp && scheduleTimeRegex.test('15:15') && scheduleTimeRegex.test('03:05') && !scheduleTimeRegex.test('15:60') && !scheduleTimeRegex.test('3:15')],
  ['Scheduler validates time zone client-side', app.includes('function validateCalendarSchedule') && app.includes("new Intl.DateTimeFormat('en-US', { timeZone })")],
  ['Scheduler validates time zone server-side', backend.includes("new Intl.DateTimeFormat('en-US', { timeZone })") && backend.includes('Reporting schedule time zone')],
  ['Scheduler stores calendar reminder minutes', backend.includes('reminderMinutes: clampNumber') && app.includes('Calendar reminder') && app.includes('reminderMinutes: Number(value)')],
  ['Scheduler offers Google Calendar', app.includes('Add to Google Calendar') && app.includes('calendar.google.com/calendar/render')],
  ['Scheduler offers Outlook Calendar', app.includes('Open in Outlook') && app.includes('outlook.office.com/calendar/0/deeplink/compose')],
  ['Scheduler offers recurring ICS download', app.includes('Download Recurring .ICS') && app.includes('function buildCalendarInvite') && app.includes('RRULE:FREQ=WEEKLY')],
  ['Scheduler avoids five-minute Forge polling', !manifest.includes('scheduledTrigger') && app.includes('No background Forge polling is required')],
  ['Assistant is floating instead of toolbar action', app.includes('assistant-launcher') && !app.includes('disabled={!report}>\n              StatusDeck Assistant')],
  ['Assistant opens without a generated report', app.includes('Ask without generating a report.') && !app.includes('{assistantOpen && report ? (')],
  ['Assistant clears submitted question immediately', app.includes("setAssistantQuestion('');") && app.indexOf("setAssistantQuestion('');") < app.indexOf("setAssistantBusy(true)" )],
  ['Assistant maintains conversational message history', app.includes('assistantMessages') && app.includes('assistant-message-${message.role}') && app.includes("role: 'user'") && app.includes("role: 'assistant'")],
  ['Assistant keeps lightweight sprint context', app.includes('assistantContext') && app.includes('Context: ${assistantContext.projectKey}')],
  ['Assistant supports contextual follow-up buttons', app.includes('assistantFollowUps') && app.includes('assistant-followups') && app.includes('submitAssistantQuestion(action)')],
  ['Assistant resolves named projects and sprints', app.includes('resolveAssistantProject({') && assistantEntity.includes('extractAssistantProjectPhrase') && app.includes('findAssistantSprint') && assistantContext.includes('getAssistantSprintReferences')],
  ['Assistant searches other Scrum boards only for named sprint', app.includes('Named sprints can live on another Scrum board') && app.includes('candidateSprints') && app.includes('targetBoard = candidateBoard')],
  ['Assistant can compare sprints', app.includes('Completion difference:') && app.includes('Compare Sprint 50 and Sprint 51')],
  ['Assistant has Jira snapshot resolver without formal report generation', backend.includes("'getAssistantSprintSnapshot'") && backend.includes('assistant_sprint_query')],
  ['Assistant snapshot resolver does not consume report quota', !backend.substring(backend.indexOf("'getAssistantSprintSnapshot'"), backend.indexOf("'getReportSchedule'")).includes("consumeUsage(context, 'report')")],
  ['Assistant uses no external AI API', !app.toLowerCase().includes('openai.com') && !app.toLowerCase().includes('gemini')],
  ['Assistant never falls back when an explicit project is unresolved', app.includes('I did not fall back to the currently selected project') && app.includes('projectResolution.explicit')],
  ['Assistant handles project phrases such as summary of Retail Banking project', assistantEntity.includes('extractAssistantProjectPhrase') && assistantProjectPhraseRegex.exec('summary of Retail Banking project')?.[1] === 'Retail Banking'],
  ['Assistant treats What about Insurance project as a fresh explicit project', assistantProjectPhraseRegex.exec('What about Insurance project?')?.[1] === 'Insurance' && assistantEntity.includes('about|from')],
  ['Assistant responses use structured headings and bullets', assistantResponse.includes('Sprint summary') && assistantResponse.includes('Remaining work') && assistantResponse.includes('Risk summary') && assistantResponse.includes('• Completion:')],
  ['Overall RAG renders before Sprint progress in Executive Pulse', app.indexOf('overall-rag-pill') >= 0 && app.indexOf('overall-rag-pill') < app.indexOf('sprint-progress-title') && css.includes('grid-template-columns: auto minmax(130px, auto)')],
  ['Scheduler exposes IANA timezone dropdown', app.includes('STATUSDECK_TIME_ZONES') && app.includes('Asia/Kolkata') && app.includes('America/New_York') && app.includes('getStatusDeckTimeZoneOptions(reportSchedule.timeZone)')],
  ['Scheduler defaults unsaved schedules to browser timezone', app.includes("const browserTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'") && app.includes('schedule.updatedAt ? schedule.timeZone : (browserTimeZone')],
  ['Export destination dialog offers Download and Confluence', app.includes('Choose Where This Report Should Go') && app.includes('Publish to Confluence') && app.includes('exportDestination')],
  ['Main toolbar uses one Export / Publish action', app.includes("'Export / Publish'") && !app.includes("'Full PowerPoint'") && !app.includes("'Full PDF'")],
  ['Confluence page parser accepts space overview homepageId URLs', confluencePageIdRegex.exec('https://example.atlassian.net/wiki/spaces/SR/overview?homepageId=8782024')?.[1] === '8782024' && app.includes('(?:pageId|homepageId)')],
  ['Confluence publishing uses Forge bridge as current user', app.includes('requestConfluence') && app.includes('/wiki/api/v2/pages/${pageId}')],
  ['Confluence publishing reads and updates page storage content', app.includes('body-format=storage') && app.includes("method: 'PUT'") && app.includes("representation: 'storage'") && app.includes('version: { number: currentVersion + 1')],
  ['Confluence page scopes declared', manifest.includes('read:page:confluence') && manifest.includes('write:page:confluence')],
  ['Jira required and Confluence optional compatibility declared', manifest.includes('compatibility:') && manifest.includes('jira:\n      required: true') && manifest.includes('confluence:\n      required: false')],
  ['No unapproved collaboration clipboard fallback remains', !app.includes('Copy for Confluence / SharePoint') && !app.includes('copyReportForCollaboration')],
  ['Existing PowerPoint and PDF generators remain the download path', app.includes("if (exportFormat === 'pdf') await handlePdfExport()") && app.includes('else await handlePowerPointExport()')],
  ['Confluence publishing generates both PDF and PowerPoint attachments', app.includes('generateConfluenceReportFiles') && app.includes("pdf.output('blob')") && app.includes("pptx.write({ outputType: 'blob' })")],
  ['Confluence publishing uploads multipart attachments through Forge bridge', app.includes('/wiki/rest/api/content/${pageId}/child/attachment') && app.includes("'X-Atlassian-Token': 'nocheck'") && app.includes('new FormData()') && app.includes("method: 'PUT'" )],
  ['Confluence attachment filenames are stable across re-publish', app.includes('buildConfluenceAttachmentFileName') && app.includes('_StatusDeck_Report.${extension}') && !app.substring(app.indexOf('function buildConfluenceAttachmentFileName'), app.indexOf('function addPptText')).includes('toISOString().slice(0, 10)')],
  ['Confluence page links to attached PDF and PowerPoint', app.includes('<ri:attachment ri:filename=') && app.includes('PDF executive report') && app.includes('Editable PowerPoint')],
  ['Confluence attachment scopes declared', manifest.includes('read:content-details:confluence') && manifest.includes('write:attachment:confluence')],
  ['Confluence publish success dialog present', app.includes('Report Published Successfully') && app.includes('Open Confluence Page') && app.includes('publishSuccess')],
  ['Last successful publication is persisted and displayed', backend.includes("'saveLastPublication'") && backend.includes("'getLastPublication'") && app.includes('Last published: Confluence') && app.includes('lastPublication')],
  ['Confluence re-publish tracks attachment version semantics', app.includes('Stable PDF/PPT filenames are reused so Confluence keeps attachment version history') && app.includes('buildConfluenceAttachmentFileName')],
  ['Assistant context catalogue derives aliases dynamically from accessible Jira projects', assistantEntity.includes('buildAssistantProjectCatalogue') && app.includes('assistantProjectCatalogue = useMemo') && !assistantEntity.includes("insurance: 'SD")],
  ['Assistant scope-first parser recognises summary of insurance without hardcoded mapping', assistantScopeFirstRegex.exec('give me summary of insurance')?.[1] === 'insurance' && assistantEntity.includes('summary|status|details?|overview|report|health')],
  ['Assistant supports fuzzy project token matching', assistantEntity.includes('assistantLevenshtein') && assistantEntity.includes('distance <= threshold')],
  ['Assistant normalization/context/entity/intent pipeline runs before Jira fetches', (() => { const start = app.indexOf('async function submitAssistantQuestion'); const normalize = app.indexOf('normalizeAssistantInput(question)', start); const references = app.indexOf('resolveConversationalReferences(', start); const intent = app.indexOf('resolveAssistantIntent(', start); const resolver = app.indexOf('resolveAssistantProject({', start); const boardsFetch = app.indexOf('getAssistantBoards(targetProject)', start); return start >= 0 && normalize > start && references > normalize && intent > references && resolver > intent && boardsFetch > resolver; })()],
  ['Assistant caches board and sprint metadata to avoid repeated Forge calls', app.includes('assistantBoardsCache') && app.includes('assistantSprintsCache') && app.includes('getAssistantBoards(targetProject)') && app.includes('getAssistantSprints(targetBoard, sprintMetadataLimit)')],
  ['Assistant board/sprint catalogue metadata uses direct Jira bridge instead of backend resolver', app.includes('requestJira') && app.includes('/rest/agile/1.0/board?projectKeyOrId=') && app.includes('/sprint?startAt=${startAt}') && !app.substring(app.indexOf('async function getAssistantBoards'), app.indexOf('async function fetchAssistantSnapshot')).includes("invoke('getBoards'") && !app.substring(app.indexOf('async function getAssistantBoards'), app.indexOf('async function fetchAssistantSnapshot')).includes("invoke('getSprints'")],
  ['Assistant messages render structured headings and lists', app.includes('renderAssistantMessageText(message.text)') && app.includes('assistant-answer-heading') && css.includes('.assistant-answer-list')],
  ['Context Catalogue preloads Confluence spaces directly through bridge', app.includes("fetchConfluenceCollection('/wiki/api/v2/spaces?limit=250&status=current'") && app.includes('no Forge resolver/runtime invocation')],
  ['Confluence space read scope declared', manifest.includes('read:space:confluence')],
  ['Confluence parent pages load lazily only for selected space', app.includes('/spaces/${encodeURIComponent(confluenceSpaceId)}/pages?limit=250') && app.includes('confluencePagesCache')],
  ['Confluence publish dialog selects space and parent page', app.includes('Confluence Space</span><select') && app.includes('Parent Page</span><select') && app.includes('Sprint child page')],
  ['Confluence Sprint child title is derived from sprint number', app.includes('function getConfluenceSprintPageTitle') && app.includes('return sprintMatch ? `Sprint ${sprintMatch[1]}`')],
  ['Confluence creates child page with selected parentId', app.includes("requestConfluence('/wiki/api/v2/pages'") && app.includes('parentId: String(parentPage.id)')],
  ['Confluence reuses existing matching Sprint child page', app.includes('String(page.parentId) === String(parentPage.id)') && app.includes('normaliseAssistantLookup(page.title) === normaliseAssistantLookup(title)')],
  ['Confluence dedicated Sprint page replaces its own body with full native report', app.includes('Publishing the full report to Confluence') && app.includes("body: { representation: 'storage', value: reportStorage }")],
  ['Confluence native page contains full report sections before attached files', app.indexOf("'<h2>Management Commentary</h2>'") >= 0 && app.indexOf("'<h2>Sprint Work Items</h2>'") > app.indexOf("'<h2>Management Commentary</h2>'") && app.indexOf("'<h2>Full Report Files</h2>'") > app.indexOf("'<h2>Sprint Work Items</h2>'")],
  ['Confluence success stores actual child page webui link', app.includes('updatedPage?._links?.webui') && app.includes('target.page?._links?.webui')],
  ['Last publication tracks space parent and child page metadata', backend.includes('spaceName: String(payload?.spaceName') && backend.includes('parentPageTitle: String(payload?.parentPageTitle') && app.includes('publishSuccess.parentPageTitle')],
  ['Assistant handles normalization and acknowledgement small talk before Jira lookup', (() => { const start = app.indexOf('async function submitAssistantQuestion'); const small = app.indexOf('classifySmallTalk(normalizedInput.normalized)', start); const jira = app.indexOf('const targetBoards = await getAssistantBoards(targetProject)', start); return assistantNormalize.includes("['thnx', 'thanks']") && assistantSmallTalk.includes('ACKNOWLEDGEMENTS') && small > start && jira > small; })()],
  ['Assistant renders colour-coded RAG callout', app.includes('assistant-rag-callout') && app.includes('assistant-rag-${ragClass}') && css.includes('.assistant-rag-red') && css.includes('.assistant-rag-amber') && css.includes('.assistant-rag-green')],
  ['Assistant renders semantic coloured headings and list markers', app.includes('getAssistantVisualTone') && app.includes('assistant-answer-heading-${tone}') && app.includes('assistant-answer-list-item-${tone}') && css.includes('.assistant-answer-heading-danger') && css.includes('.assistant-answer-list-item-warning::marker')],
  ['Confluence uses canonical wiki child-page URLs', app.includes('function buildConfluenceCanonicalPageUrl') && app.includes('`/wiki/spaces/${encodeURIComponent(key)}/pages/${encodeURIComponent(id)}${titlePath}`') && app.includes('buildConfluenceCanonicalPageUrl(target.space.key, pageId, publishedPageTitle')],
  ['Confluence success action canonicalizes old and new publication links', app.includes('buildConfluenceCanonicalPageUrl(publishSuccess.spaceKey, publishSuccess.pageId, publishSuccess.pageTitle, publishSuccess.pageUrl)')],
  ['Confluence native report includes coloured status macros', app.includes('function confluenceStatusMacro') && app.includes('ac:name="status"') && app.includes("confluenceStatusMacro(overall.label, ragColour)")],
  ['Confluence native report includes coloured executive panels', app.includes('function confluencePanelMacro') && app.includes('ac:name="panel"') && app.includes("title: `Overall RAG · ${overall.label}`") && app.includes("title: 'Executive Commentary'")],
  ['Confluence KPI table uses compact headers and wider layout', app.includes("['RAG', 'Completion', 'Health', 'Scope', 'Done', 'Remaining', 'Open', 'Overdue', 'Defects']") && app.includes(']], 900)') && app.includes('data-table-width')],
  ['Confluence report files are presented in a coloured native panel', app.includes("title: 'Published Report Files'") && app.includes("confluenceStatusMacro('PDF', 'Blue')") && app.includes("confluenceStatusMacro('PPTX', 'Blue')")],
  ['Assistant helper modules extracted from monolithic App', assistantNormalize.includes('normalizeAssistantInput') && assistantSmallTalk.includes('classifySmallTalk') && assistantContext.includes('resolveConversationalReferences') && assistantEntity.includes('resolveAssistantProject') && assistantIntent.includes('resolveAssistantIntent') && assistantResponse.includes('buildAssistantAnswer') && assistantActions.includes('assistantCommandAction')],
  ['Assistant mode dropdown defaults to Instant', app.includes("useState('instant')") && app.includes('<option value="instant">Instant</option>') && app.includes('<option value="medium">Medium</option>') && app.includes('<option value="high">High</option>')],
  ['Assistant expanded header hides implementation subtitle', app.includes('assistant-title') && !app.includes('Jira delivery assistant · local deterministic logic · no external AI')],
  ['Assistant header uses StatusDeck blue treatment', css.includes('linear-gradient(120deg, #0b2f5b') && css.includes('.assistant-panel-chat .assistant-title strong')],
  ['Assistant hides internal analysis mode from normal answers', !assistantResponse.includes('Analysis mode:') && !app.includes('Analysis mode: ${ASSISTANT_MODES[assistantMode].label}')],
  ['Assistant velocity response includes compact visual data', assistantResponse.includes("visual: rows.length ? { type: 'velocity'") && app.includes('renderAssistantVisual(message.visual)') && css.includes('.assistant-mini-velocity')],
  ['Assistant modes control analysis depth not answer length only', assistantIntent.includes('maxSprintMetadata') && assistantIntent.includes('maxHistoricalSprints') && assistantIntent.includes("fetchVelocity: intent === 'VELOCITY'")],
  ['Assistant Instant metadata loading is bounded', assistantIntent.includes("safeMode === 'instant' ? 100") && app.includes('all.length < maxItems')],
  ['Assistant High historical analysis remains bounded', assistantIntent.includes("safeMode === 'medium' ? 4 : 6")],
  ['Assistant unknown conversational text clarifies before Jira fetch', app.includes('Unknown conversational text should never trigger a Jira fetch') && app.includes("intent.type === 'UNKNOWN' && !projectResolution.explicit")],
  ['Assistant pronoun resolution handles this/it before entity search', assistantContext.includes('hasPronoun') && assistantContext.includes("sprintReference = 'context'") && app.indexOf('resolveConversationalReferences(') < app.indexOf('resolveAssistantProject({')],
  ['Assistant generate-report intent becomes a real StatusDeck action', assistantIntent.includes('GENERATE_REPORT') && app.includes("'Generate Executive Report'") && app.includes("'generate-report'") && app.includes('assistantPendingReportRef')],
  ['Assistant publish intent opens existing Export / Publish flow', assistantIntent.includes('PUBLISH') && app.includes("setExportModalOpen(true)") && app.includes("assistantCommandAction('Open Export / Publish', 'publish'")],
  ['Assistant small talk never updates Jira context or sets busy before response', (() => { const start = app.indexOf('async function submitAssistantQuestion'); const small = app.indexOf('const smallTalk = classifySmallTalk', start); const busy = app.indexOf('setAssistantBusy(true)', start); return small > start && busy > small; })()],
  ['Assistant understands future sprint list intent', assistantIntent.includes('LIST_FUTURE_SPRINTS') && app.includes("intent.type === 'LIST_FUTURE_SPRINTS'") && app.includes('Upcoming sprints')],
  ['Assistant future sprint listing is metadata-only', assistantIntent.includes("'LIST_FUTURE_SPRINTS', 'SELECT_SPRINT'") && assistantIntent.includes('metadataOnly') && assistantIntent.includes("'LIST_FUTURE_SPRINTS', 'SELECT_SPRINT', 'UNSUPPORTED_KPI'") && assistantIntent.includes("'LIST_FUTURE_SPRINTS', 'SELECT_SPRINT', 'UNSUPPORTED_KPI', 'CARRY_OVER'")],
  ['Assistant recognises next/upcoming/previous temporal language', assistantContext.includes('getAssistantTemporalRequest') && assistantContext.includes("type: 'future-list'") && assistantContext.includes("type: 'next'") && assistantContext.includes("type: 'previous'")],
  ['Assistant stores future sprint choices for conversational selection', app.includes('lastSprintChoices') && app.includes("lastIntent: 'LIST_FUTURE_SPRINTS'") && assistantContext.includes('listChoiceIndex')],
  ['Assistant supports ordinal follow-ups such as second one', assistantIntent.includes('SELECT_SPRINT') && app.includes("intent.type === 'SELECT_SPRINT'") && app.includes('I will use ${targetSprint.name} for your next question')],
  ['Assistant follow-ups include future sprint discovery when available', assistantActions.includes("case 'SPRINT_SUMMARY'") && assistantActions.includes("'Show future sprints'") && app.includes('availableFutureSprints')],
  ['Assistant future sprint follow-ups include summary load generate and compare', assistantActions.includes('Summarize ${first.name}') && assistantActions.includes('Load ${first.name}') && assistantActions.includes('Generate report for ${first.name}') && assistantActions.includes('Compare ${first.name} with ${currentSprint}')],
  ['Assistant normalization covers production shorthand and common typos', assistantNormalize.includes("['nxt', 'next']") && assistantNormalize.includes("['futre', 'future']") && assistantNormalize.includes("['upcomming', 'upcoming']") && assistantNormalize.includes("['summry', 'summary']")],
  ['Assistant asks clarification instead of Jira fetch for unknown text', app.includes('I am not sure what you want me to do with that') && app.indexOf('I am not sure what you want me to do with that') < app.indexOf('setAssistantBusy(true)', app.indexOf('async function submitAssistantQuestion'))],
  ['Assistant Agile knowledge layer is separated from App', assistantAgileKnowledge.includes('AGILE_CONCEPTS') && assistantIntent.includes('detectAgileConcept')],
  ['Assistant recognises burndown as first-class Agile intent', assistantAgileKnowledge.includes("id: 'BURNDOWN'") && assistantAgileKnowledge.includes("intent: 'BURNDOWN'")],
  ['Assistant recognises commitment vs delivery', assistantAgileKnowledge.includes("id: 'COMMITMENT_DELIVERY'")],
  ['Assistant recognises carry-over and uses existing next-sprint outlook only on demand', assistantAgileKnowledge.includes("id: 'CARRY_OVER'") && app.includes("intent.type === 'CARRY_OVER'") && app.includes("invoke('getNextSprintOutlook'")],
  ['Assistant recognises Agile KPIs without inventing unsupported metrics', assistantAgileKnowledge.includes("id: 'CYCLE_TIME'") && assistantAgileKnowledge.includes("intent: 'UNSUPPORTED_KPI'") && app.includes('buildUnsupportedAgileAnswer')],
  ['Assistant supports status/type/priority KPI families', assistantAgileKnowledge.includes("id: 'STATUS_DISTRIBUTION'") && assistantAgileKnowledge.includes("id: 'ISSUE_TYPES'") && assistantAgileKnowledge.includes("id: 'PRIORITY_DISTRIBUTION'")],
  ['Assistant supports predictability with bounded analysis', assistantAgileKnowledge.includes("id: 'PREDICTABILITY'") && assistantIntent.includes("intent === 'PREDICTABILITY'") && assistantIntent.includes('maxHistoricalSprints')],
  ['Assistant Agile follow-ups are adaptive', assistantActions.includes("case 'BURNDOWN'") && assistantActions.includes("case 'PREDICTABILITY'") && assistantActions.includes("case 'CARRY_OVER'")],
  ['Project report uses executive health model', app.includes('Executive / Program Health') && app.includes('Project Health at a Glance')],
  ['Project report has data-generated editable management commentary', app.includes('projectNarrativeText') && app.includes('ProjectManagementSummary') && app.includes('saveProjectCommentary') && app.includes('Restore Generated')],
  ['Project commentary persists independently from sprint commentary', app.includes("boardId: 'project-program'") && app.includes("sprintId: 'project-program'")],
  ['Project report sections use deterministic move menu', app.includes('projectSectionHandleProps') && app.includes('moveProjectSectionByDirection') && app.includes('statusdeck-project-section-order-v2')],
  ['Project paired sections support Left/Right movement like Sprint overview cards', app.includes('PROJECT_FULL_WIDTH_SECTION_IDS') && app.includes('buildProjectSectionRows') && app.includes("direction === 'left' && availability.left") && app.includes("direction === 'right' && availability.right")],
  ['Project full-width sections remain full-width while analytical peers can pair', app.includes("'projectHealth'") && app.includes("'projectCommentary'") && app.includes("'projectDelivery'") && app.includes("'projectTeams'") && css.includes('grid-template-columns: repeat(2, minmax(0, 1fr));')],
  ['Project report exposes project-specific section selector', app.includes('ProjectSectionSelector') && app.includes('Project report sections')],
  ['Project report keeps velocity team-level instead of aggregating it', app.includes('Velocity is displayed per team rather than aggregated across boards')],
  ['Project report derives team RAG from configured thresholds', app.includes('deriveProjectTeamHealth') && app.includes('rag.redOverdue') && app.includes('rag.greenCompletion')],
  ['Project report analyses scope movement from sprint history', app.includes('scopeDeltaItems') && app.includes('originalCommitment?.items') && app.includes('currentScope?.items')],
  ['Project report analyses blocked and unresolved defect signals from actual issues', app.includes('blockedStatusCount') && app.includes('unresolvedDefectCount')],
  ['Project report loads Jira epics and versions only on project-report demand', backend.includes('getProjectPortfolioContext') && app.includes("portfolioContextPromise = invoke('getProjectPortfolioContext'")],
  ['Project portfolio context avoids issue history scans', backend.includes('Lightweight project/program context') && backend.includes('issuetype = Epic') && backend.includes('/versions')],
  ['Project report has release and milestone section without invented readiness percentage', app.includes('Release & Milestone Readiness') && app.includes('does not infer a release-readiness percentage')],
  ['Project report has operational flow and capacity section', app.includes('Operational Flow & Capacity') && app.includes('Pipeline Health and Workload')],
  ['Project report has quality risk dependencies section', app.includes('Quality, Risks & Dependencies')],
  ['Project KPIs expose actual calculation previews', app.includes('projectMeanCompletion') && app.includes('projectOverdue') && app.includes('projectOverallRag') && app.includes('projectTeamCompletion')],
  ['Project mean completion preview shows team-value arithmetic', app.includes("teamCompletionValues.join(' + ')") && app.includes('displayed ${projectView.meanCompletion}%')],
  ['Project scope growth is guarded when sprint-start baseline is unavailable', app.includes('hasScopeBaseline') && app.includes('Scope baseline unavailable.') && app.includes('does not treat all current items as scope added')],
  ['Project commentary editor is full-width and visually aligned with Sprint commentary', css.includes('.project-commentary-editor {') && css.includes('width: 100%;') && css.includes('min-height: 220px;')],
  ['Project operational flow reuses StatusDeck visual language', app.includes('<StatusDonut statusCounts={projectView.statusCounts}') && app.includes('<ProjectWorkloadBars workload={projectView.workload} />')],
  ['Empty Epic and Release sections collapse to compact information strips', app.includes('project-empty-strip') && css.includes('.project-empty-section')],
  ['Loaded Project report suppresses the generic report-preview empty state', app.includes(') : !projectReport ? (')],
  ['Project report visual system matches Sprint report cards and blue methodology accent', css.includes('Project / Program Report visual alignment with the stable Sprint Report') && css.includes('border-left-color: var(--sd-blue);')],
  ['Selected Sprint fetches Acceptance Criteria evidence only inside selected sprint scope', backend.includes('includeDescription: true, acceptanceCriteriaFieldId: acceptanceCriteriaField.id') && backend.includes("includeDescription ? 'description' : null") && backend.includes('report-cache-v6')],
  ['Acceptance Criteria detection supports headings and Given-When-Then without external AI', backend.includes('function detectAcceptanceCriteria') && backend.includes('acceptance-criteria-heading') && backend.includes('given-when-then') && backend.includes('summarizeAcceptanceCriteria')],
  ['Acceptance Criteria analysis is Story-level and returns coverage plus flagged keys', backend.includes('function isStoryForAcceptanceCriteria') && backend.includes('coveragePercentage') && backend.includes('missingKeys') && backend.includes('noDescriptionKeys')],
  ['Acceptance Criteria analysis counts individual criteria and explicit task states', backend.includes('totalCriteria') && backend.includes('metCriteria') && backend.includes('notMetCriteria') && backend.includes('unrecordedCriteria') && backend.includes('trackableCriteria')],
  ['Acceptance Criteria supports Markdown checkboxes and Jira ADF task items', backend.includes("block.kind === 'task'") && backend.includes("type === 'taskItem'") && backend.includes("match(/^[-*+]\\s*\\[([xX ])\\]")],
  ['Sprint report displays AC total, Met, Not met and status-not-recorded counts', app.includes('Criteria Identified') && app.includes('✓ Met') && app.includes('× Not Met') && app.includes('○ Status Not Recorded') && app.includes('AcceptanceCriteriaSummary')],
  ['PowerPoint export includes Acceptance Criteria counts when Stories are available', app.includes("'Acceptance Criteria',") && app.includes("label: 'Status Not Recorded'") && app.includes('pptAcceptanceCriteria')],
  ['Confluence native report includes Acceptance Criteria counts and interpretation', app.includes('acceptanceCriteriaSection') && app.includes('Acceptance Criteria Interpretation') && app.includes('StatusDeck does not infer completion from prose or Story status.')],
  ['Active and closed Sprint reports include Acceptance Criteria Completion panel', app.includes("report.sprint.state !== 'future' ? (") && app.includes('title="Acceptance Criteria Completion"')],
  ['Future Sprint readiness includes individual Acceptance Criteria detail', app.includes('title="Acceptance Criteria Detail"') && app.includes('criteria have no explicit Jira completion state')],
  ['Generated Sprint commentary uses actual AC Met/Not met/unrecorded counts', app.includes('criteria are explicitly Met') && app.includes('explicitly marked Not met') && app.includes('no recorded completion state')],
  ['Acceptance Criteria cache versions invalidate older summary payloads', backend.includes('report-cache-v6:') && backend.includes('outlook-cache-v5:')],
  ['Future Sprint readiness includes Acceptance Criteria coverage and flagged Stories', app.includes('Future Sprint Readiness Checks') && app.includes('Stories Needing Acceptance Criteria') && app.includes('acceptanceCriteriaCoverage') && app.includes('Open Flagged Stories in Jira')],
  ['Acceptance Criteria readiness threshold is configurable and validated', app.includes('minimumAcceptanceCriteriaCoverage: 80') && app.includes('Minimum Story Acceptance Criteria Coverage %') && app.includes('Minimum Acceptance Criteria coverage must be between 0 and 100%.') && backend.includes('minimumAcceptanceCriteriaCoverage')],
  ['Next Sprint outlook includes Acceptance Criteria readiness without scanning unrelated Jira work', backend.includes('const acceptanceCriteria = summarizeAcceptanceCriteria(nextMetrics.reportingIssues ?? [])') && app.includes('Acceptance Criteria') && app.includes('nextSprintOutlook.acceptanceCriteria')],
  ['Future Sprint generated commentary is data-driven for Acceptance Criteria gaps', app.includes('Acceptance Criteria are identifiable in') && app.includes('Complete Acceptance Criteria: Refine the flagged Stories before sprint activation')],
  ['Acceptance Criteria calculation help explains coverage and explicit completion-state rules', app.includes("title: 'Acceptance Criteria Coverage'") && app.includes("title: 'Acceptance Criteria Completion'") && app.includes('Plain-text criteria are never inferred as Met or Not met.')],
  ['Acceptance Criteria source can be mapped to Description or Jira custom text field', app.includes('Acceptance Criteria source') && app.includes('acceptanceCriteriaFieldId') && backend.includes('acceptanceCriteriaFields') && backend.includes('resolveAcceptanceCriteriaField')],
  ['Acceptance Criteria threshold drives explicit quality readiness risk', app.includes('Quality readiness risk: Acceptance Criteria coverage is') && app.includes('below the configured')],
  ['Traceability section is included in executive report and export', app.includes("id: 'traceability'") && app.includes('Traceability & Quality Evidence') && app.includes('Story-to-Delivery Traceability') && app.includes('traceabilitySection')],
  ['Traceability uses Jira evidence rather than inferred test status', backend.includes('summarizeTraceability') && backend.includes('linkedIssues') && backend.includes('fixVersions') && app.includes('Missing Jira links are shown as gaps rather than inferred.')],
  ['Executive briefing is presentation-first and shows reporting basis', app.includes('function ExecutiveBriefing') && app.includes('Executive Summary') && app.includes('Reporting Basis:') && css.includes('.executive-briefing-card')],
  ['Present mode makes management commentary read-only', app.includes('readOnly={presentationMode}') && app.includes('ExecutiveCommentaryPreview') && css.includes('.presentation-mode .no-export')],
  ['Estimation override labels propagate to executive and export units', app.includes('getEstimationDisplay(report)') && app.includes('Completed ${estimationDisplay.short}') && app.includes('current ${estimationDisplay.short}')],
  ['Saved commentary is fingerprinted against report snapshot', app.includes('function getReportFingerprint') && backend.includes('reportFingerprint') && app.includes('commentaryStale')],
  ['Customer permission document matches current Confluence-enabled manifest', permissionsDoc.includes('write:page:confluence') && permissionsDoc.includes('write:attachment:confluence') && permissionsDoc.includes('No Jira issue/project write scope')],
  ['Stale clipboard/backup deployment instructions removed from customer docs', !deploymentDoc.includes('backup/original-production-baseline') && !deploymentDoc.includes('Copy for Confluence / SharePoint') && !limitationsDoc.includes('copies management-ready text to the clipboard')],
  ['Security and data-flow docs disclose deterministic Assistant and no external egress', securityDoc.includes('does not call an external LLM') && privacyFlowDoc.includes('does not declare external egress domains')],
  ['Data-retention doc accurately distinguishes persistent settings and short-lived caches', retentionDoc.includes('Persistent application records') && retentionDoc.includes('Short-lived cache records') && retentionDoc.includes('There is no recurring cleanup job')],
  ['Custom Jira Insights supports native KPI selection', app.includes('Bring Your Jira Reporting into StatusDeck') && app.includes('native-kpi-grid')],
  ['Custom Jira Insight controls moved out of Configuration', app.includes('Build the Report Around Your Jira') && app.includes('Custom Jira Insights') && !app.includes('<CustomKpiStudio draft={draft} setDraft={setDraft} sources={kpiSources}')],
  ['Custom KPI UI defaults to issue count without calculation selector', !app.includes('<span>Calculation</span>') && app.includes("aggregation: 'count'")],
  ['KPI Studio discovers saved Jira filters and dashboards', backend.includes('getJiraKpiSources') && backend.includes('/rest/api/3/filter/search') && backend.includes('/rest/api/3/dashboard/search')],
  ['Custom Jira Insight evaluation uses saved filter IDs without rewriting JQL', backend.includes('filter = ${filterId}') && backend.includes('buildCustomInsightJql') && !backend.includes('jql = String(filter?.jql')],
  ['Custom JQL is executed exactly as entered without report scoping', backend.includes('const rawJql = String(definition?.jql') && backend.includes('return { jql: rawJql }')],
  ['Custom Jira Insights preserve Jira source scope without adding report project/sprint constraints', backend.includes('function buildCustomInsightJql') && backend.includes('return { jql: `filter = ${filterId}` }') && !backend.includes('function buildScopedCustomKpiJql')],
  ['Dashboard insight catalogue preserves gadget visual metadata', backend.includes('detectDashboardGadgetType') && backend.includes('gadgetType') && backend.includes('statisticType') && backend.includes('xStatistic') && backend.includes('yStatistic')],
  ['Dashboard pie and two-dimensional insights render in StatusDeck', app.includes("insight.viewType === 'pie'") && app.includes("insight.viewType === 'twoDimensional'") && app.includes('CustomJiraInsightsSection')],
  ['Custom Jira Insights modal selects dashboard gadget identity instead of only filter ID', app.includes('Select Dashboard Gadget…') && app.includes('dashboardId:source.dashboardId') && app.includes('gadgetId:source.gadgetId')],
  ['One invalid custom Jira insight returns a per-card error without failing all insights', backend.includes('results.push({ id, name, error: countResult.error, jql })') && backend.includes('Custom Jira insight evaluation failed unexpectedly')],
  ['Custom Jira dashboard insights use enhanced JQL search and never call removed /rest/api/3/search', backend.includes('/rest/api/3/search/jql') && !backend.includes('route`/rest/api/3/search`') && backend.includes('nextPageToken')],
  ['Project report download export is enabled', app.includes('createProjectPowerPoint') && app.includes('createProjectPdf') && app.includes('(!report && !projectReport)')],
  ['Project and Sprint reuse the same Confluence publish workflow', app.includes('buildProjectConfluenceStorageReport') && app.includes('resolveConfluenceReportPage') && app.includes("project-program") && !app.includes('Project/Program Confluence publishing is not enabled')],
  ['Sprint PowerPoint scope export defines commitment baseline before use', app.includes('const baselineReliable = original > 0 || current === 0;') && app.includes('report.metrics.committedStoryPoints ?? history.currentScope?.storyPoints')],
  ['Project loader analyses boards in parallel', app.includes('Promise.allSettled(targetBoards.map')],
  ['Report loading shows real staged progress', app.includes('statusdeck-progress-panel') && app.includes('loadingProgress.percent')],
  ['Executive export caps change history to five entries', app.includes('.slice(0, 5)') && app.includes('Executive change summary')],
  ['PPT combines Velocity and Team workload', app.includes('Velocity & Team Workload') && app.includes('compactPeople')],
  ['Premium Executive palette is present', app.includes("blue: '2457A6'") && css.includes('--sd-premium-navy')],
  ['Custom Jira Insights remain in Sprint report flow below Executive Pulse and use movable section ordering', app.lastIndexOf('results={customKpiResults}') > app.indexOf('<SprintProgressStrip') && app.includes("sectionProps('customJiraInsights'") && app.includes("sectionHandleProps('customJiraInsights')")],
  ['Custom Jira Insights participate in unified report generation', app.includes('evaluateConfiguredInsightsForReport') && app.includes("await evaluateConfiguredInsightsForReport('sprint'") && app.includes("await evaluateConfiguredInsightsForReport('project'")],
  ['Custom KPI evaluation failures remain visible as cards', app.includes('buildCustomKpiErrorRows') && app.includes('custom-kpi-card-error')],
  ['Custom Jira Insights avoid Forge resolver aggregation', app.includes('no Forge resolver/runtime invocation') && !app.includes("invoke('evaluateCustomKpis', args)")],
  ['Reporting settings state initializes before unified insight generation', app.indexOf('const [reportingSettings, setReportingSettings] = useState(DEFAULT_REPORTING_SETTINGS);') < app.indexOf('evaluateConfiguredInsightsForReport')],
  ['Heavy Jira insight paging uses direct Forge Bridge requestJira', app.includes("requestJira('/rest/api/3/search/jql'") && app.includes('evaluateCustomJiraInsightsDirect')],
  ['Custom Jira Insight aggregate snapshot is cached in tab memory', app.includes('customInsightCacheRef = useRef(new Map())') && app.includes('cache?.set(acc.cacheKey, row)')],
  ['Custom Jira Insight UI exposes progressive aggregation state', app.includes('custom-kpi-card-loading') && app.includes('Jira items aggregated')],
  ['Saved filter selection auto-populates editable insight name', app.includes("name:filter?.name || item.name || 'Custom Jira Insight'")],
  ['Dashboard gadget selection auto-populates editable insight name', app.includes("name:source.gadgetTitle || item.name || 'Custom Jira Insight'")],
  ['Days remaining is exposed as a configurable native KPI', app.includes("daysRemaining: 'Days Remaining'") && app.includes('showDaysRemaining={reportingSettings.kpiProfile?.native?.daysRemaining !== false}')],
  ['Created vs Resolved dashboard gadget has dedicated line renderer', app.includes("viewType === 'createdResolved'") && app.includes('custom-jira-created-line') && app.includes('resolutiondate')],
  ['Days Remaining dashboard gadget is discovered without a saved filter', backend.includes("gadgetType !== 'daysRemaining'") && app.includes("viewType === 'daysRemaining'")],
  ['Custom Jira Insights are hidden until unified report generation completes', app.includes('Custom Jira Insights are evaluated inside the report-generation pipeline') && !app.includes('Jira insights loading separately')],
  ['Large dashboard reconstruction has a 12,500-issue browser-side guardrail', app.includes('DIRECT_INSIGHT_MAX_ISSUES = 12500') && app.includes('DIRECT_INSIGHT_REPORT_MAX_ISSUES = 12500') && backend.includes('hardCap = 12500')],
  ['Created vs Resolved legacy dashboard definitions are upgraded from count fallback to line type', app.includes('normaliseDirectDashboardGadgetType') && app.includes("${definition?.name || ''}") && app.includes("sourceText.includes('created vs. resolved')") && app.includes("return 'createdResolved'")],
  ['Days Remaining legacy dashboard definitions are recognised and can use selected report sprint context', app.includes("return 'daysRemaining'") && app.includes('context?.sprintId') && app.includes('context?.boardId')],
  ['Days Remaining avoids browser-side Agile requestJira decoding path', app.includes("await invoke('getSprints', { boardId: Number(boardId) })") && !app.includes("requestJira(`/rest/agile/1.0/sprint/${encodeURIComponent(explicitSprintId)}`")],
  ['Days Remaining reuses already loaded sprint metadata before backend fallback', app.includes('Array.isArray(context?.sprints) ? context.sprints : []') && app.includes('sprints.find((item) => String(item.id) === String(sprintId))')],
  ['Created vs Resolved uses date-bucket count queries instead of downloading the saved-filter population', app.includes('evaluateCreatedResolvedByCounts') && app.includes('buildCreatedResolvedRangeJql') && app.includes("getCachedDirectJqlCount(task.jql") && app.includes("unit: 'date-counts'") && app.includes('if (!issueLevelRich.length) continue')],
  ['Created vs Resolved displays chart-window count separately from broad source-filter count', app.includes('in chart window') && app.includes('source filter ≈') && app.includes('sourceFilterCount')],
  ['Created vs Resolved chart ticks avoid adjacent final date labels', app.includes('getCreatedResolvedTickIndices(points, 7)') && !app.includes('Math.ceil(points.length / 8)')],
  ['Sprint PDF export includes Custom Jira Insights visuals', app.includes('addPdfCustomJiraInsightPages(doc, customKpiResults') && app.includes('pdfCreatedResolvedInsight') && app.includes('customJiraPdfPageRef')],
  ['Sprint PowerPoint export includes Custom Jira Insights visuals', app.includes('addPptCustomJiraInsightSlides({ pptx, customKpiResults, pageRef })') && app.includes('addPptCreatedResolvedInsight')],
  ['Custom Jira Insights are movable in Sprint report section order', app.includes("id: 'customJiraInsights'") && app.includes("sectionProps('customJiraInsights'") && app.includes("sectionHandleProps('customJiraInsights')")],
  ['Custom Jira Insights are movable in Project report section order', app.includes("id: 'projectCustomJiraInsights'") && app.includes("projectSectionStyle('projectCustomJiraInsights')") && app.includes("projectSectionHandleProps('projectCustomJiraInsights')")],
  ['Sprint + Project insights are inherited into Project / Program reports', app.includes('boardSettingsOutcomes') && app.includes("['both', 'project'].includes(item.target ?? 'both')") && app.includes('effectiveProjectSettings')],
  ['Project commentary uses executive at-a-glance presentation', app.includes('buildProjectExecutiveCommentarySnapshot') && app.includes('Project Executive Commentary') && app.includes('outlookTitle="Release / Milestone Outlook"')],
  ['Project commentary editor is collapsed behind an explicit edit action', app.includes("showCommentaryEditor ? 'Close editor' : 'Edit commentary'") && app.includes('Edit Project Narrative')],
  ['Executive commentary readability is increased for stakeholders', css.includes('font-size: 15px;') && css.includes('font-size: 24px;') && css.includes('stakeholder readability v3')],
  ['Confluence avoids deprecated legacy Chart macro for new Cloud pages', !app.includes('ac:name="chart"') && !app.includes('function confluenceChartMacro')],
  ['Confluence publishes Created vs Resolved as attached PNG visual', app.includes('renderConfluenceCreatedResolvedPng') && app.includes('confluenceAttachmentImage') && app.includes('Created vs. Resolved')],
  ['Confluence publishes Pie custom insight as attached PNG visual', app.includes('renderConfluencePiePng') && app.includes("insight.viewType === 'pie'") && app.includes("'image/png'")],
  ['Confluence chart image attachment filenames are stable for re-publish', app.includes('buildConfluenceInsightImageFileName') && app.includes('StatusDeck_Custom_Insight_')],
  ['Confluence publishes Two Dimensional custom insight as native table', app.includes("insight.viewType === 'twoDimensional'") && app.includes('confluenceTable(headers, rows, 900)')],
  ['Created vs Resolved PPT line segments normalise negative-height segments to avoid PowerPoint repair/misrendering', app.includes('addChartLineSegment') && app.includes('flipV: y2 < y1') && app.includes('Math.abs(y2 - y1)')],
  ['Sprint export calls pass Custom Jira Insight results to PDF and PPT', app.includes('createPdfReport({ report, velocityReport, nextSprintOutlook') && app.includes('createPowerPoint({ report, velocityReport, nextSprintOutlook') && app.match(/customKpiResults,\n\s*reportingSettings/g)?.length >= 2],
  ['Dashboard source persistence includes module key for future gadget-type recovery', app.includes("moduleKey:source.moduleKey||\'\'")],
  ['Saving Custom Jira Insights reuses the visible report snapshot instead of rebuilding Sprint/Velocity/Outlook', app.includes('async function refreshCustomInsightsOnly(settings)') && app.includes('await refreshCustomInsightsOnly(mergedSaved);') && app.includes('native KPI visibility')],
  ['Unchanged Custom Jira Insight results are reused from tab cache during save', app.includes('customInsightCacheRef.current') && app.includes('if (cache?.has(cacheKey)) { results.push')],
  ['Legacy saved dashboard definitions self-heal from the current Jira gadget catalogue', app.includes('Self-heal dashboard definitions saved by older builds') && app.includes('gadgetType: source.gadgetType || normaliseDirectDashboardGadgetType(item)')],
  ['Persisted dashboard insight metadata retains moduleKey for gadget recovery', backend.includes("moduleKey: String(item?.moduleKey || '').slice(0, 240)")],
  ['Custom Jira Insight results are committed before the Sprint report becomes visible', app.indexOf('setCustomKpiResults(nextCustomKpiResults);') < app.indexOf('setReport(sprintResult);')],
  ['Title Case naming is used for core report section labels', app.includes("label: 'Executive Overview'") && app.includes("label: 'Sprint Scope History'") && app.includes("label: 'Detailed Burndown'") && app.includes("label: 'Sprint Report'") && app.includes("label: 'Team Workload'") && app.includes("label: 'Sprint Work Items'")],
  ['Title Case naming is used in Executive Summary and Commentary UI', app.includes('>Executive Summary</p>') && app.includes('>Management Commentary</p>') && app.includes('>Executive Commentary</h3>') && app.includes('>Key Risks</h4>') && app.includes('>Recommended Actions</h4>')],
  ['Title Case naming is used for project/program headings', app.includes('>Executive / Program Health</p>') && app.includes('>Project Health at a Glance</h3>') && app.includes('>Release & Milestone Readiness</p>')],
  ['Title Case naming is used in report exports', app.includes("'Executive Overview'") && app.includes("'Effort Estimate and Variance'") && app.includes("'Velocity & Team Workload'") && app.includes("'Traceability & Quality Evidence'")],
  ['Strict Title Case is used for delivery status labels', app.includes("'At Risk'") && app.includes("'Watch Closely'") && app.includes("'On Track'") && app.includes("'Delivered With Concerns'") && app.includes("'Below Commitment'") && !app.includes("'At risk'") && !app.includes("'Watch closely'") && !app.includes("'On track'")],
  ['Strict Title Case is used for core interactive controls', app.includes('>Report Type</span>') && app.includes('>Report Sections</span>') && app.includes('Reporting Scheduler') && app.includes('Load Report') && app.includes('Save Jira Insights') && app.includes('Save Configuration')],
  ['Strict Title Case is used for Acceptance Criteria and traceability labels', app.includes('>Stories With AC</span>') && app.includes('>Criteria Identified</span>') && app.includes('>× Not Met</span>') && app.includes('>○ Status Not Recorded</span>') && app.includes('>Parent / Requirement Linked</span>') && app.includes('>Linked Test Evidence</span>') && app.includes('>Release / Fix Version Mapped</span>') && app.includes('>Open Linked Defects</span>')],
  ['Strict Title Case is used for configuration labels', app.includes('>Estimation Override</span>') && app.includes('>Green Completion ≥ %</span>') && app.includes('>Amber Unresolved Defects</span>') && app.includes('>Maximum Next-Sprint Velocity Load %</span>') && app.includes('>Acceptance Criteria Source</span>') && app.includes('>Restore Defaults</button>')],
  ['Complete Title Case applies to dynamic status surfaces', app.includes('titleCaseUiLabel(deliveryStatus?.label') && app.includes('titleCaseUiLabel(deliveryStatus.label)') && app.includes('titleCaseUiLabel(snapshot.statusLabel)')],
  ['Complete Title Case applies to executive at-a-glance labels', app.includes('>At a Glance</div>') && app.includes('titleCaseUiLabel(item.label)') && app.includes('titleCaseUiLabel(callout.label)')],
  ['Complete Title Case applies to primary report controls', app.includes('Reporting Scheduler') && app.includes('Load Report') && !app.includes('>Reporting scheduler<')],
  ['Complete Title Case applies to detailed Sprint controls', app.includes('Story Points') && app.includes('Remaining Effort') && app.includes('Live Events') && app.includes('Full Table')],
  ['Complete Title Case applies to report action labels', app.includes('Open Core Gaps in Jira') && app.includes('View Latest Jira History Changes') && app.includes('Open Confluence Page')],
  ['CSS braces balanced', (css.match(/{/g) || []).length === (css.match(/}/g) || []).length],
];

let failed = 0;
for (const [name, ok] of checks) {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}`);
  if (!ok) failed += 1;
}

if (failed) {
  console.error(`\n${failed} regression check(s) failed.`);
  process.exit(1);
}
console.log(`\n${checks.length} regression checks passed.`);
